# Generated by Django 5.0.6 on 2024-07-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='default', max_length=50, unique=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('bin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.EmailField(max_length=50, null=True)),
                ('item_description', models.CharField(max_length=100, null=True)),
                ('bin_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.restaurant')),
            ],
        ),
    ]
