# Generated by Django 5.0.6 on 2024-07-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0002_sessiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_value', models.PositiveBigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('order_desription', models.CharField(max_length=50)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.customuser')),
            ],
        ),
    ]
