# Generated by Django 5.0.6 on 2024-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_value', models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
