# Generated by Django 5.0.6 on 2024-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_uploadedimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
