# Generated by Django 5.0.6 on 2024-09-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_restaurant_menu_restaurant_id_menu_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
